version: '3'
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 420:80
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: drupal
    volumes:
      - kit23dbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  kit23dbdata: